version: '3.8'

volumes:
  apex_neo4j_data:
  apex_redis_data:

networks:
  apex_net:
    driver: overlay
    attachable: true

services:
  # Elixir Applications
  apex_dash:
    image: "bgottlob/apex_dash:latest"
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      APEX_BROADCAST_HOST: tasks.apex_broadcast
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==docker-swarm-manager"
    networks:
      - apex_net
    depends_on:
      - apex_broadcast

  apex_broadcast:
    image: "bgottlob/apex_broadcast:latest"
    ports:
      - "20777:20777/udp"
    environment:
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==docker-swarm-manager"
    networks:
      - apex_net

  apex_redis_streamer:
    image: "bgottlob/apex_redis_streamer:latest"
    environment:
      APEX_BROADCAST_HOST: tasks.apex_broadcast
      APEX_REDIS_URI: "redis://:${APEX_REDIS_PASSWORD}@tasks.apex_redis:6379"
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==redis-node"
    networks:
      - apex_net
    depends_on:
      - apex_broadcast
      - redis

  apex_neo4j_adapter:
    image: "bgottlob/apex_neo4j_adapter:latest"
    environment:
      APEX_BROADCAST_HOST: tasks.apex_broadcast
      APEX_BOLT_URI: "bolt://${APEX_BOLT_USERNAME}:${APEX_BOLT_PASSWORD}@tasks.apex_neo4j:7687"
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==neo4j-node"
    networks:
      - apex_net
    depends_on:
      - apex_broadcast
      - neo4j

  # Databases
  redis:
    image: "redis:6.0-alpine"
    command: "redis-server --requirepass ${APEX_REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - "apex_redis_data:/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==redis-node"
    networks:
      - apex_net

  neo4j:
    image: "neo4j:4.1"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "${APEX_BOLT_USERNAME}/${APEX_BOLT_PASSWORD}"
    volumes:
      - "apex_neo4j_data:/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==neo4j-node"
    networks:
      - apex_net

  # Flink cluster
  jobmanager:
    image: flink:1.11-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==flink-node"
    environment:
      APEX_REDIS_HOST: tasks.apex_redis
      APEX_REDIS_PORT: 6379
      APEX_REDIS_PASSWORD: ${APEX_REDIS_PASSWORD}
      FLINK_PROPERTIES: "jobmanager.rpc.address: tasks.jobmanager"
    networks:
      - apex_net

  taskmanager:
    image: flink:1.11-scala_2.12
    command: taskmanager
    environment:
      APEX_REDIS_HOST: tasks.apex_redis
      APEX_REDIS_PORT: 6379
      APEX_REDIS_PASSWORD: ${APEX_REDIS_PASSWORD}
      FLINK_PROPERTIES: "jobmanager.rpc.address: tasks.jobmanager"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==flink-node"
    networks:
      - apex_net
    depends_on:
      - jobmanager
