version: '3.8'

volumes:
  apex_neo4j_data:

networks:
  apex_net:
    driver: bridge

services:
  # Elixir Applications
  apex_dash:
    image: "bgottlob/apex_dash:latest"
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      APEX_BROADCAST_HOST: apex_broadcast
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    networks:
      - apex_net
    depends_on:
      - apex_broadcast

  apex_broadcast:
    image: "bgottlob/apex_broadcast:latest"
    ports:
      - "20777:20777/udp"
    environment:
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    networks:
      - apex_net

  apex_neo4j_adapter:
    image: "bgottlob/apex_neo4j_adapter:latest"
    environment:
      APEX_BROADCAST_HOST: apex_broadcast
      APEX_BOLT_URI: "bolt://${APEX_BOLT_USERNAME}:${APEX_BOLT_PASSWORD}@neo4j:7687"
      MIX_ENV: ${MIX_ENV}
      ERLANG_COOKIE: ${ERLANG_COOKIE}
    networks:
      - apex_net
    depends_on:
      - apex_broadcast
      - neo4j

  # Databases
  neo4j:
    image: "neo4j:4.1"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "${APEX_BOLT_USERNAME}/${APEX_BOLT_PASSWORD}"
    volumes:
      - "apex_neo4j_data:/data"
    networks:
      - apex_net
